In [1]:
import numpy

In [3]:
world_school = numpy.genfromtxt('world_alcohol.txt',delimiter=',',dtype=str)
print(world_school)
print(type(world_school))

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
<class 'numpy.ndarray'>


In [6]:
vector = numpy.array([5,10,15,20])
matrix = numpy.array([[5,10,15],[20,25,30]])
print(vector)
print(matrix)

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]]


In [8]:
vector.dtype


dtype('int32')

In [9]:
world_school

array([['Year', 'WHO region', 'Country', 'Beverage Types',
        'Display Value'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ...,
       ['1987', 'Africa', 'Malawi', 'Other', '0.75'],
       ['1989', 'Americas', 'Bahamas', 'Wine', '1.5'],
       ['1985', 'Africa', 'Malawi', 'Spirits', '0.31']], dtype='<U52')

In [11]:
world_school_1956 = world_school[1,4]
third_country = world_school[2,2]
print(world_school_1956)
print(third_country)

0
Uruguay


In [12]:
print(vector[0:3])

[ 5 10 15]


In [14]:
print(matrix[0:2])
print(matrix[:,1])
print(matrix[1][1])

[[ 5 10 15]
 [20 25 30]]
[10 25]
25


In [18]:
matrix2 = numpy.array([[1,2,3,4,5],[2,4,6,8,9],[9,3,4,5,6],[2,3,5,7,5]])
print(matrix2)

[[1 2 3 4 5]
 [2 4 6 8 9]
 [9 3 4 5 6]
 [2 3 5 7 5]]


In [19]:
print(matrix2[0:2])

[[1 2 3 4 5]
 [2 4 6 8 9]]


In [21]:
print(matrix2[:,1])

[2 4 3 3]


In [23]:
print(matrix2[:,0:2])

[[1 2]
 [2 4]
 [9 3]
 [2 3]]


In [24]:
print(matrix2[1:3,2:4])

[[6 8]
 [4 5]]


In [26]:
a = numpy.zeros((3,4,5))
print(a.shape)
print(a.dtype)

(3, 4, 5)
float64


In [30]:
b = matrix2.ravel()
print(b)

[1 2 3 4 5 2 4 6 8 9 9 3 4 5 6 2 3 5 7 5]
